### ISSUE TITLE
Avoid committing changes to 'generated on' lines

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/chaste-codegen#108]
Hiding these by default in the GitHub diff is good, but we can use git filters to avoid putting them in the commit in the first place. See e.g. https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#_keyword_expansion for full details.

In `.gitattributes` we'd want something like
```
*.hpp filter=strip_gen_time
*.cpp filter=strip_gen_time
```

Then in our docs tell developers to set up the filter:
```sh
git config --global filter.strip_gen_time.clean 'sed "s;^//! on .*;//! on (date omitted as unimportant);"'
git config --global filter.strip_gen_time.smudge cat
```

What do you think @MauriceHendrix ?

**Comment by MauriceHendrix** [comment]
hhm if things go wrong i can be useful to be able to look at whether the reference files have changed though.

**Comment by jonc125** [comment]
You'd still see if there were any substantive changes to the reference files - the only line it affects is the generated on timestamp. So if `git diff` gives you nothing then you know the timestamp is the only thing that might have changed.

**Comment by MauriceHendrix** [comment]
aah I see and if any developers didn't follow the instructions <cough> something I might do</cough> it would still work (it just wouldn't strip out the timestamp?

**Comment by jonc125** [comment]
Exactly.

**Comment by MauriceHendrix** [comment]
ok i'll set it up

**Comment by MauriceHendrix** [comment]
@jonc125 aah obviously I don't have sed (I'm on windows)
