### ISSUE TITLE
Codegen integration in chaste

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/chaste-codegen#156]
Gary and I have been discussing linking codegen to chaste. There are a few things we want to get your opinion on @jonc125 .

Firstly we were looking at the lookup tables, which are currently not implemented. What's your opinion on how important it would be and how difficult?

In terms of steps to get codegen linked up:
- figure out how the dynamic build process currently works
- figure out how to get cmake to use python3 somehow
- find a way somehow to indicate what type of model codegen should build without making config files somehow...
- translate other python files (I think that's mostly done)
- looks like we need a way to get codegen to build a default selection of models (currently done with ConvertCellModel.py, but a way built into codegen that wouldn't require re-loadin the cllmlmanip model would be nice
- update the wiki page about code generation

**Comment by jonc125** [comment]
Re lookup tables, depends on whether users want it! The analysis for when to use them is very simple. With sympy I'd suggest doing something similar to the interpolation support in weblab-fc, and introduce a new class of Dummy to represent an expression replaced by a lookup table, that can store the info you need (keying var, original expression, steps, etc) and the templating step can generate the appropriate code. You need one part of the output generating the tables, so being able to loop over all tables in the model, and then whenever a TableDummy is encountered in an expression you generate the lookup instead. I wouldn't bother with all the optional variations, just go with the default settings which were found to be most efficient.

**Comment by jonc125** [comment]
Updating codegen to allow multiple output types should just be an extension to (or a new) CLI interface; the library shouldn't need many changes. You could allow multiple instances of -t for instance.
