### ISSUE TITLE
possible speed up CVODE cells by sharing terms between EvaluateYDerivatives and EvaluateAnalyticJacobian

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/chaste-codegen#201]
Since each call to `EvaluateAnalyticJacobian` in chaste is proceeded every a call (with the same parameters) `EvaluateYDerivatives`, it seemed resonable to assume, as @mirams suggested, that a speedup could be acheived by caching common terms in the possible `EvaluateYDerivatives` call and using them in the `EvaluateAnalyticJacobian` call.

However we tested this idea and results show a slowdown rather than speedup. The old timings below are without the treatment described above.
```
375: CVODE  time: 3.52249s
375: CVODE old time: 3.40852s
375: CVODE ForceUseOfNumericalJacobian time: 4.41097s
375: CVODE ForceUseOfNumericalJacobian old time: 4.22725s
375: CVODE lookup tables time: 3.49791s
375: CVODE lookup tables old time: 2.78594s
375: CVODE lookup tables ForceUseOfNumericalJacobian time: 4.43238s
375: CVODE lookup tables ForceUseOfNumericalJacobian old time: 3.21403s
```

[ten_tusscher_model_2006_endo.txt](https://github.com/ModellingWebLab/chaste-codegen/files/6036765/ten_tusscher_model_2006_endo.txt)

[TestCodegen.txt](https://github.com/ModellingWebLab/chaste-codegen/files/6036766/TestCodegen.txt)

**Comment by mirams** [comment]
See also https://chaste.cs.ox.ac.uk/trac/ticket/3059

**Comment by mirams** [comment]
Closing this as a 'wontfix' for now, see the Chaste ticket above for details on timings. In essence, there's not much point caching extra things as CVODE doesn't call the jacobian anywhere near as many times as the EvaluateYDerivs...
