### ISSUE TITLE
Automatic code generation for dynamic clamp platforms 

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/chaste-codegen#21]
See https://github.com/ModellingWebLab/project_issues/issues/42

@mirams wrote:

> Dynamic clamp platforms use real-time computing to inject simulated currents into real cells, and take voltage from real cells as an input over the next time interval.
> 
> A common use case is a sub-model like a sodium current from a whole AP model, or a whole AP model that is missing particular currents. Our Functional Curation framework should be able to export these nicely, and already makes a sub-model Chaste .hpp and .cpp files from a given input and outputs.
>
> We would want to generate code with fixed-time solvers like Rush-Larsen / RK4 in a format for some dynamic clamp platforms.
>
>I manually ‘flattened’ (combined the abstract class and solver with the concrete ODE system) one of our Rush-Larsen models for Teun in Utrecht, and he translated from C++ to Labview, this was a bit laborious. It would be a very nice application of FC framework to just be able to export him any current module from any model in a format he could readily use. I would like this to be a feature of Web Lab that people could use like they do for whole models in PMR at the moment. Other dynamic clamp softwares include David Christini’s RTXi and Randy Rasmusson also has some dynamic clamp software. All would probably want a similar 'flattened' optimised compute time model, but we can check that with them.
>
> (A nice optional extra would be to do R-L style exact solves on Markov models automatically too with old-school linear system eigenvalues/vectors etc. over fixed V timesteps. Might need some clever business to assemble a transition matrix from randomly written equations, work out maple analytic expressions for eigenvalues and vectors etc. This would also be great for our parameter fitting exercises as it would speed up calculations with voltage steps massively.)

**Comment by mirams** [comment]
We can have a chat about this one at some point Maurice - needs much the same stuff as chaste-cg

**Comment by MauriceHendrix** [comment]
Ideally I'd like to try and do one thing at a time if possible. Can we delay discussing this until we at least have some of the basics of cg for chaste working?

**Comment by mirams** [comment]
Yeah, one for the future.

**Comment by mirams** [comment]
I think we got a good long way with this one with LabView code generated - maybe to document a bit here.

**Comment by MauriceHendrix** [comment]
we did. It's been possible to generateboth labview code and C code using:
```
--rush-larsen-labview
Generate rush-larsen-labview model type in mastrcriptRT with added injection current(i_inj)

  --rush-larsen-c
Generate rush-larsen-c model type in C with added injection current(i_inj)
```
