### ISSUE TITLE
Implement Chaste model export

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/chaste-codegen#3]
To do
- [x] Add simple template for .hpp files normal models (default vector type `std::vector<double>`)
- [x] Write test that comapres generated .hpp against a PyCml generated reference
- [x] Add simple template for .cpp files normal models
- [x] Write test that compares generated .cpp against a PyCml generated reference (new tests added together with new features)
- [x] Add C++ expression printer, based on WebLabPrinter
- [x] Add GetIIonic method (a subset of ComputeDerivedQuantities used in tissue simulations) there is some fancy business working out what currents are relevant (right hand side of dV/dt equation).
- [x] Use Chaste units - voltage in mV, time in ms, current as per https://chaste.cs.ox.ac.uk/trac/wiki/ChasteGuides/ChasteUnits, Ca_i
- [x] Repeat above for Cvode cells - Numerical Jacobian (`N_Vector`). Option `-t CVODE`; class `CellMLToCvodeTranslator`.
- [x] Repeat above for Cvode cells with Analytic Jacobian. Options `-t CVODE`, `-j`.
    - Jacobian calculation in `cellmlmanip` (done in pycml with `-J` using Maple) using sympy
- [x] Repeat above for Opt models: re-implement lookup tables. Options `-l` and `optimize.py`.
    - [x] Implemented a version of partial evaluation as a separate phase for now.
    - [x] Lookup tables
- [x] Repeat above for Backwards Euler models. (use a special Jacobian related to the one above with Identity matrix minus delta_t*one above). Options `-t Chaste`, `-j`, `--backward-euler`.
- [x] Add ComputeDerivedQuantities method - should be similar in implementation to WebLab GetOutputs.
- [x] Add Rush-Larsen cells (requires gating variables with exact solution over fixed V to be identified, with tags or - even better - by analysing the equations). Option `--rush-larsen`.
- [x] Add Generalised Rush Larsen cells (see TestPyCmlLongGeneralisedRushLarsenFirstOrder). 
- [x] Add Generalised Rush Larsen second order cells (see TestPyCmlLongGeneralisedRushSecondOrder).
- [x] Look at compiling on the fly ("dynamically loaded") by using new Python 3 code instead of PyCML). Option `-y`.
- [x] Other specialist cell types - DataClamp (`--use-data-clamp`)
- [x] Other specialist cell types - WithModifiers (`--use-modifiers`)
- [x] Complex unit conversion rules via cellmlmanip
- [x] Use ontology to tag currents (besides stimulu_current)
- [x] Fix sympy1.6 warnings and other warnings as much as possible
- [x] Update github documentation (especially command line instructions etc.)
- [x] Packaging chaste_codegen to enable districution
- [x] Setting up cmake/make system to use chaste_codegen
- [x] PyCML replacement ready for Python 3 (note on https://chaste.cs.ox.ac.uk/trac/ticket/2991)
- [x] Deal with and fix singularities in equations

**Comment by mirams** [comment]
I don't think this is something you should distract yourself with at the moment (although nice to have in the back of your mind when working on cellmlmanip). 

In fact I thought it would be a nice introductory task to leave for new Nottingham RSE to get up to speed with Chaste and Web Lab tools?

**Comment by mirams** [comment]
I've updated the checklist with a suggested order

**Comment by jonc125** [comment]
> I've updated the checklist with a suggested order

So backward Euler is more important than data clamp & modifiers?

**Comment by mirams** [comment]
Probably, not sure anyone is using any of them very much, but seems a pity to loose capabilities. The modifiers were supposed to be replaced with functional curation + WL anyway

**Comment by jonc125** [comment]
Testing for this issue will be trickier than with the Web Lab code-gen, because you can't run simulations without Chaste available. So possibly tests within this repo should just compare the generated code against reference versions created by pycml, at least initially?

**Comment by MauriceHendrix** [comment]
> Testing for this issue will be trickier than with the Web Lab code-gen, because you can't run simulations without Chaste available. So possibly tests within this repo should just compare the generated code against reference versions created by pycml, at least initially?

That was my thinking indeed, as otherwise we'd also need both python 2 and 3 as well as the obsolute libs we're trying to get away from.

**Comment by MauriceHendrix** [comment]
I'm just updating this and makring in progress items as bold.

**Comment by MauriceHendrix** [comment]
first release:
https://pypi.org/project/chaste-codegen/
still to do: the link up with the chaste build system & python3 translation of other python bits

**Comment by MauriceHendrix** [comment]
I reopened this  because:
- it is easier to find this way and can be useful for reference
- we're working on dealing with singularities in equations
