### ISSUE TITLE
Split tests into short dev suite, and longer nightly tests

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/chaste-codegen#30]
Nightly ones can be run with a cronjob in travis, see #20 

For example

Dev tests:
- Run the unit tests, e.g. the ones that test 1 unit of code
- Run a few larger tests, e.g. generating code from a model

Nightly tests:
- Run tests on several models, to test we didn't break anything, or new dependencies break stuff etc.

**Comment by MichaelClerx** [comment]
@jonc125 says:

> You can set tests to be skipped unless an env var is set or similar
> Using standard pytest functionality

**Comment by MauriceHendrix** [comment]
> @jonc125 says:
> 
> > You can set tests to be skipped unless an env var is set or similar
> > Using standard pytest functionality

yes indeed (I actually use it to skip my development test). How would we set it up would you run nightly tests on the master or...?

**Comment by jonc125** [comment]
Yes, a Travis cron run on the master branch with the env var set would be the way to go I think.

**Comment by MauriceHendrix** [comment]
done!
