### ISSUE TITLE
Simplify tests for generators

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/chaste-codegen#37]
At the moment, we're using fairly complex tests that check whether the equations are functionally equivalent to the ones in code generated by pycml.

**In the long run**, these should be replaced by unit tests for smaller chunks of code, and tests that simply compare the generator output to a stored previous (manually validated) output

**Comment by MauriceHendrix** [comment]
In general I agree however unit tests for private internals are generally not commended and I don't really want to make everything public.
There are still some things we can do in smaller unit tests though of course.

**Comment by MauriceHendrix** [comment]
Changed to use direct comparison and a separate test in chaste to verify models are correct. The original test is skipped and can still be used as a development tool.
