### ISSUE TITLE
hodgkin_huxley_squid_axon_model_1952_modified version without annotation used in weblab test

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/chaste-codegen#40]
test_weblab_templating uses an older version of hodgkin_huxley_squid_axon_model_1952_modified without annotation.
It would be nice to have all cellml files in 1 place, but currently not possile as the cellml folder in chaste_cg branch) has a version of the model with annotation and the test fails on this version (probably due to naming issues)

**Comment by mirams** [comment]
Can't you just use the exact same folder of cellml files that pycml did for the test suite?

**Comment by MauriceHendrix** [comment]
We're talking python purest, when well link it up to chaste well definitely change the minimum :)
