### ISSUE TITLE
Split CG: Move Printer to cellmlmanip, move weblab stuff into `cg`, keep this as a chaste code generator

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/chaste-codegen#54]
Lots of questions! Mostly for @jonc125 :smile: 

- Should we move bits about variable guessing from annotations from the chaste generator into `cellmlmanip`?   (A bit like [myokit.lib.guess](https://github.com/MichaelClerx/myokit/blob/master/myokit/lib/guess.py))
- Should bits of unit conversion move there too? Have they already?
- Should `cg` have any brains at all? From a WL perspective it makes more sense to do lots of things to the cellmlmanip model in `fc`, and then just pass it in for conversion to code. But the `chaste` code does lots of clever things. Should it stay that way or should there be some other program that uses `cellmlmanip` and `cg` the way `fc` does to generate chaste models from the command line? Or should `fc` pass off more of its duties to `cg` ?

**Comment by MichaelClerx** [comment]
The reason I think it makes sense for `fc` to be "smart" is that it reads fc protocol files to get information about which units it wants etc. It also reads the cellmlmanip model. It could then either do things itself, or ask `cg` or `cellmlmanip` but that means some more messy communication.

But for chaste I guess desires outputs and units etc. are all hardcoded?

**Comment by MauriceHendrix** [comment]
> The reason I think it makes sense for `fc` to be "smart" is that it reads fc protocol files to get information about which units it wants etc. It also reads the cellmlmanip model. It could then either do things itself, or ask `cg` or `cellmlmanip` but that means some more messy communication.
> 
> But for chaste I guess desires outputs and units etc. are all hardcoded?

Yes at the moment in the dictionaries at the top so they're easy to find and change.

**Comment by MichaelClerx** [comment]
It might even make sense to decide `cg` should be part of `cellmlmanip` - but only as a lightweight templating tool, maybe including a python printer, maybe just having a printer interface that users need to supply an implementation for.

Then `fc` could have its own templates and printer living inside `fc`, and the chaste code generator could have its templates, printer, and logic living inside a chaste code generating tool?

**Comment by MichaelClerx** [comment]
The design of `chaste_cg` was always a bit up in the air :sweat_smile: 
Now that it's a bit more clear how we're using it's beginning to look like two projects in the same repo, with only a small bit of shared code. So seems to logical design is to merge that shared code with `cellmlmanip` and then split the project in two?

**Comment by mirams** [comment]
My gut instinct is "when it's finished"! That way you don't have to keep two things that use cellmlmanip tested and in sync with changes in cellmlmanip, and you don't have people breaking chaste_cg underneath Maurice, or vice-versa. It should be pretty similar with Chaste cg asking for certain interface units etc. as a special case of the more general weblab_cg.

**Comment by jonc125** [comment]
I'd agree with @mirams not to restructure the repos yet! Although moving the common `cg` code into `cellmlmanip` probably does make sense longer term, with a basic printer to subclass, and the WebLab-specific code gen into `weblab-fc`. It's not clear where the Chaste-specific code gen will go - maybe into Chaste itself, for instance?

As for specific questions:

* Variable guessing should stay with the Chaste code gen, as it's very specific to that. It didn't get used in WL1, for instance. So '`chaste_cg`' will need some brains :)
* Units conversion will be able to move into `cellmlmanip` once @skeating's current PR is merged.

**Comment by MichaelClerx** [comment]
I think it'd make everyone's life a bit easier to do this soonish though.
Maurice would go from working on "cg + cellmlmanip" to "chaste_cg + cellmlmanip" and not have to worry about WL stuff inside "chaste_cg".
For FC it would mean that all the stuff related to FC model code (the model base class and the templates that create models that implement it) are in one place

**Comment by MichaelClerx** [comment]
We could even just rename this repo to `chaste_cg` or something similar, and slowly move other things out

**Comment by jonc125** [comment]
I'd be OK with moving WebLab-specific stuff into `weblab-fc` as convenient. Let's avoid renaming repos and moving Maurice's stuff yet though.

**Comment by MauriceHendrix** [comment]
Weglab_cg feels like a decent enough fit to me since we're reusing most of the printing and using the same templates.
Also if we either want others to use cellmlmanip or the other extreme replace it with libcellml it might be quite convenient for me not being the same repo

**Comment by MichaelClerx** [comment]
> I'd be OK with moving WebLab-specific stuff into `weblab-fc` as convenient. Let's avoid renaming repos and moving Maurice's stuff yet though.

Half-doing stuff is the last thing I want! Desperately seeking some clarity in this project hence these proposals :-)

**Comment by MichaelClerx** [comment]
> Also if we either want others to use cellmlmanip or the other extreme replace it with libcellml it might be quite convenient for me not being the same repo

Just to clarify my suggestion:
- The only bits of code the chaste and weblab printers current share are the method `cg.load_template` and the `cg.Printer` class. I'm suggesting these two move to cellmlmanip.
- This means that others who want to use cellmlmanip can still do so, and can now also use `load_template` and the `Printer` for their own code generation
- The `weblab` templates would move into `fc`
- The `chaste` templates would stay here or move into some other repo

So you wouldn't have any chaste stuff in the cellmlmanip repo!

And there's no plan to replace cellmlmanip with libcellml, only to replace the parser class in cellmlmanip with something that uses libcellml

**Comment by MauriceHendrix** [comment]
> > Also if we either want others to use cellmlmanip or the other extreme replace it with libcellml it might be quite convenient for me not being the same repo
> 
> Just to clarify my suggestion:
> 
> * The only bits of code the chaste and weblab code generators currently share are the method `cg.load_template` and the `cg.Printer` class. I'm suggesting these two move to cellmlmanip.
> * This means that others who want to use cellmlmanip can still do so, and can now also use `load_template` and the `Printer` for their own code generation
> * The `weblab` templates would move into `fc`
> * The `chaste` templates would stay here (and then this would become the chaste code generation repo) or move into some other repo (and then this repo would be deleted)
> 
> So you wouldn't have any chaste stuff in the cellmlmanip repo!
> 
> And there's no plan to replace cellmlmanip with libcellml, only to replace the parser class in cellmlmanip with something that uses libcellml

Aah I suppose that's a decent idea. I would probably prefer chaste_cg code not to be developed in the chase repositories for now  as a) we'd have 2 different code generators there to confuse everybody and 
b) changes would trigger fairly slow C++ tests rather than out python tests which gare much quicker and give me more useful errors during dev

**Comment by MichaelClerx** [comment]
That makes sense to me!

**Comment by MichaelClerx** [comment]
Another good reason for splitting now would be that Maurice gets a place to explain derived quantities etc. and other concepts that exist in chaste generation, and can do nice examples and documentation and stuff.
I think this is pretty important if you want to avoid another big rewrite in a couple of years

**Comment by jonc125** [comment]
I'm becoming convinced 😄 on the basis that it's a quick change to make and has several benefits. I'll try to look at it a bit more next week - I don't think we should do this before Christmas, let's get the current in-progress PRs merged, but could do in early Jan.

**Comment by MauriceHendrix** [comment]
Actually I'm onlu working 2 more days this year and I need to catch up with admin stuff & stuff for my other team so pretty much done programming for 2019 after today :)

**Comment by MichaelClerx** [comment]
(Worth noting that if you rename a repository, github redirects the old URLs to the new one for a very long time, so won't break any existing checkouts etc. for a few months at least)

**Comment by MichaelClerx** [comment]
One day of early Jan left :D

**Comment by MichaelClerx** [comment]
Are we still in favour of this change? @jonc125 
I think I am!

**Comment by MauriceHendrix** [comment]
I think so and it's probably a task easier done nest week when we're all in the same room.

**Comment by jonc125** [comment]
The repos are both in a fairly clear state too - no PRs open on cellmlmanip, and only 1 here.

**Comment by MichaelClerx** [comment]
Update:

- [x] Rename this repo to `chaste_codegen` #75 
- [x] Fiddle about with build tools for several hours #80 
- [ ] Create new `Printer` module on `cellmlmanip`
- [ ] Update local `Printer` classes to subclass the cellmlmanip one, remove base Printer from `cg`
- [x] ~Move `load_template` to cellmlmanip~ Discussed and decided against this: It's not a lot of code and is mostly user-specific (jinja config preferences, template directory)
- [ ] Move weblab parts into `fc`

**Comment by jonc125** [comment]
I think we can close this now @MichaelClerx ?
